[project]
name = "lss-app"
version = "0.1.0"
description = "Testinė programa"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.40",
]

[tool.uv.workspace]
members = ["help"]
